<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Darumen.Shared\Darumen.Shared.csproj" />
    <ProjectReference Include="..\RefData\Darumen.Modules.RefData.csproj" />
    <ProjectReference Include="..\Queue\Darumen.Modules.Queue.csproj" />
    <ProjectReference Include="..\Medicines\Darumen.Modules.Medicines.csproj" />
  </ItemGroup>

</Project>
