// <auto-generated />
using System;
using Darumen.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Darumen.Migrations.Migrations
{
    [DbContext(typeof(DarumenDbContext))]
    [Migration("20260910205005_Intake")]
    partial class Intake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("journal")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Darumen.Migrations.AnomalyAck", b =>
                {
                    b.Property<string>("AnomalyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anomaly_id");

                    b.Property<DateTime>("AckedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acked_at");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("AnomalyId");

                    b.ToTable("anomaly_acks", "journal");
                });

            modelBuilder.Entity("Darumen.Migrations.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("Chosen")
                        .HasColumnType("jsonb")
                        .HasColumnName("chosen");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Recommended")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Actor", "RecordedAt");

                    b.HasIndex("Subject", "SubjectId");

                    b.ToTable("decisions", "journal");
                });

            modelBuilder.Entity("Darumen.Migrations.IntakeBatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("batch_id");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dataset");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Partitions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partitions");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<long>("RowsLoaded")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_loaded");

                    b.Property<long>("RowsQuarantined")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_quarantined");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("BatchId");

                    b.HasIndex("Dataset", "ReceivedAt");

                    b.ToTable("batches", "intake");
                });
#pragma warning restore 612, 618
        }
    }
}
